name: release version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -DskipTests -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          version-patch: true

          git-release-bot-name: "phasetwo-bot"
          git-release-bot-email: "support@phasetwo.io"

          maven-args: "-e -X -DskipTests -DskipITs -Dmaven.deploy.skip=true"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: false
          gpg-key-id: EE987E9D73D27204E4F2C15359242F8D867FE304
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
